-- AlterTable
ALTER TABLE `User` ADD COLUMN `createTime` DATETIME NOT NULL DEFAULT NOW(),
    ADD COLUMN `role` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `updateTime` TIMESTAMP(0) NOT NULL DEFAULT NOW() ON UPDATE NOW();
